pipelines:
  - name: pipeline_logistics_shipment_status
    description: "Tracks a shipment status(demo)"
    steps:
      - tool: logistics.get_customer
      - tool: logistics.get_shipment
      - analyst: true